#!/usr/bin/env python3
"""
Generate the seven preview pages.

The chrome (unofficial ribbon, brand bar, the city's nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "hub":     "qmQGUpyn9LZQmdKwjAeWF6",   # both centers, every program, Facilities menu
    "ac":      "tQF06YWoAo4HDLxztRYow1",   # the outdoor Aquatics Center, Pools menu
    "crc":     "CfjPFKFbY9mY804eLoftpT",   # the CRC indoor pool
    "lap":     "c5dJvh9WnUdSPDCdjh15a2",   # Lap Swim at both centers
    "fit":     "vEXgsnQBRAFvNxupDVVR7T",   # Shallow Tone, Deep H2O Dynamics, CRC Aqua Fitness
    "lessons": "ZA813GWyAMBTXFnXtI76zF",   # Swim Lessons
    "comp":    "4nOtuEgJabUEssEWCxcGbe",   # the Competition Pool, lane by lane
    "splash":  "QoMkhkqWYDH9OxeQgqTjDk",   # Splash Youth Swim practices only, 3:30-8:30pm
}

NAV = [
    ("index.html",           "Aquatics"),
    ("aquatics-center.html", "Aquatics Center"),
    ("aqua-fitness.html",    "Aqua Fitness"),
    ("crc.html",             "CRC Aquatics"),
    ("swim-lessons.html",    "Swim Lessons"),
    ("lap-swim.html",        "Lap Swim"),
    ("splash.html",          "Splash Swim Team"),
]

AC_PDF = "https://www.morganhill.ca.gov/DocumentCenter/View/786"
CRC_PDF = "https://www.morganhill.ca.gov/DocumentCenter/View/40340"


def cal(key, title, short=False, caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    cls = "cal short" if short else "cal"
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="{cls}">
    <iframe src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a City of Morgan Hill website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a City of Morgan Hill page. A replica of the
  <a href="https://www.morganhill.ca.gov/209/Aquatics" target="_blank" rel="noopener">Morgan Hill aquatics pages</a>
  with live <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">MORGAN HILL CENTENNIAL</span>Recreation Center</a>
    <div class="tel">CRC (408)&nbsp;782-2128 &middot; Aquatics Center (408)&nbsp;782-2134</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li class="on"><a href="index.html">Aquatics</a></li>
    <li><a href="https://www.morganhill.ca.gov/2457/Centennial-Recreation-Center-CRC" target="_blank" rel="noopener">Fitness</a></li>
    <li><a href="https://www.morganhill.ca.gov/2457/Centennial-Recreation-Center-CRC" target="_blank" rel="noopener">Membership</a></li>
    <li><a href="https://www.morganhill.ca.gov/2520/Recreation-Facilities" target="_blank" rel="noopener">Parties &amp; Rentals</a></li>
    <li><a href="https://www.morganhill.ca.gov/285/Recreation-Activity-Guide" target="_blank" rel="noopener">Programs</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what the Morgan Hill aquatics pages would
    look like with a live calendar on each one. Not affiliated with the City of Morgan Hill.</p>
    <p>Schedules transcribed 23 September 2026 from the city's
    <a href="{AC_PDF}" target="_blank" rel="noopener">Aquatics Center</a> and
    <a href="{CRC_PDF}" target="_blank" rel="noopener">CRC indoor pool</a> schedules, both effective
    September 8, 2026. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


# ── The findings block, shared by the hub and the Aquatics Center page ─────────
QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics office</h2>
  <p>Everything here was transcribed from what Morgan Hill publishes. These are the places where the
  sources disagree, go quiet, or where we had to make a call &mdash; each one is also written on the
  calendar entry itself.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Deep H2O Dynamics at 11am &mdash; which lanes?</div>
      <div class="a">The class runs weekdays 11:00&ndash;11:55 in the Competition Pool, inside the
      5:00am&ndash;1:30pm lap swim block. The schedule gives lap swim &ldquo;9&ndash;17 lanes&rdquo; but
      never says which lanes the class takes. The calendar flags it until you say how the pool splits.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>The October 24 swim meet</div>
      <div class="a">Lap swim that Saturday is 5&ndash;7am, and the calendar already shows it. The make-up
      Sunday in October has no date yet, and the notice doesn't say whether Saturday water polo and the
      Instructional Pool run that day.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Splash Youth Swim &mdash; which lanes, and each group's times?</div>
      <div class="a">The team page gives Monday&ndash;Thursday &ldquo;between 4:15 and 7:55pm&rdquo; in the
      Competition Pool, which is exactly when public lap swim drops to 5 lanes. We put Splash on the other
      12 (lanes 6&ndash;17) as one block. Each group's times, and the time of Intro to Water Polo on
      Mondays and Wednesdays, would show the real practices.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>17 lanes or 18?</div>
      <div class="a">The aquatics page says the Competition Pool offers &ldquo;a minimum of 5 lanes to
      18 lanes at a time&rdquo;. The schedule tops out at 17. We built the pool with 17.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>&ldquo;9&ndash;17 lanes&rdquo; shown as 9</div>
      <div class="a">Weekday morning lap swim is shown on the 9 lanes the schedule guarantees, and
      Saturday's &ldquo;10&ndash;17&rdquo; on 10. When do the other lanes open to lap swim? Say, and
      the calendar shows each extra lane at the hour it opens.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Aqua Zumba on the first Saturday</div>
      <div class="a">The schedule notes Aqua Zumba &ldquo;on the 1st Saturday of the month&rdquo; in the
      Saturday 8am Shallow Tone slot. We read that as Aqua Zumba replacing Shallow Tone that day, and
      noted it on the class.</div>
    </li>
  </ul>
</section>

"""


# ══ 1. The hub ════════════════════════════════════════════════════════════════
HUB = f"""<section class="wrap hero">
  <div class="crumb">Parks &amp; Recreation &raquo; Aquatics</div>
  <h1>Aquatics at the CRC and Aquatics Center</h1>
  <p class="kicker">Two centers &middot; three pools &middot; one calendar</p>
  <p class="lead">Lap swim, aqua fitness, swim lessons and water polo, at the outdoor Aquatics
  Center and the indoor Centennial Recreation Center pool. Use the
  <strong>Facilities</strong> menu to narrow to one center, or leave it on <strong>All</strong>.</p>

{cal("hub", "Morgan Hill Aquatics — both pools, the whole week",
     caption="Every block shows its pool and how many lanes it takes.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Two schedules, one question</h2>
    <p class="q">&ldquo;Can I swim laps at five on Tuesday?&rdquo;</p>
    <p>Today that takes two PDFs. The outdoor schedule says lap swim runs 4&ndash;8pm on 5 lanes. The
    indoor schedule says &ldquo;Swim Lessons/Lap Swim Play Area Open: 4:15pm&ndash;6:40pm (1 Lap Lane
    Open)&rdquo;. Both are right, and a swimmer has to open both and line them up.</p>
    <p class="answer">On the calendar it's one look at Tuesday: <b>5 lanes outdoors, 1 lane indoors</b>,
    with the lessons beside it. And when a swim meet takes a Saturday, the change shows on that day
    instead of in a footnote on page two.</p>
  </div>
</div>

<section class="wrap">
  <h2>The pools</h2>
  <div class="facts">
    <div><b>CRC Indoor Pool</b>Three 20-yard lap lanes, a slide and a shallow play area. Heated to about
    83&ndash;84&deg; year round. 171 W Edmundson Avenue.</div>
    <div><b>Competition Pool</b>Outdoor, 25-yard lanes. Lap swim, deep-water aqua fitness and water polo.
    About 78&ndash;80&deg; year round. 16200 Condit Road.</div>
    <div><b>Instructional Pool</b>25 &times; 15 yards, about 84&ndash;85&deg;. Shallow-water aqua fitness
    and lap swim.</div>
    <div><b>Recreational Pool</b>Two giant slides and a water playground. Summer only; reopens
    June 5, 2027.</div>
  </div>
</section>

{QUESTIONS}"""


# ══ 2. Aquatics Center ════════════════════════════════════════════════════════
AC = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Aquatics Center</div>
  <h1>Morgan Hill Aquatics Center</h1>
  <p class="kicker">Open for lap swim and aqua fitness &middot; summer season from June 5, 2027</p>
  <p class="lead">An Olympic-size competition pool and a warm-water instructional pool, open year round;
  the recreation pool, slides and spray-ground open for summer. 16200 Condit Road &middot;
  (408)&nbsp;782-2134.</p>

{cal("ac", "Morgan Hill Aquatics Center — this week",
     caption="Use the <strong>Pools</strong> menu to switch between the Competition and Instructional pools.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The modification is already on the calendar</h2>
    <p>The Aquatics Center page says <i>&ldquo;Closures and Modified Programs: Stay tuned for future
    updates.&rdquo;</i> The one modification that exists is a sentence at the bottom of page two of the
    schedule PDF: lap swim is 5&ndash;7am on Saturday, October 24, because of a swim meet.</p>
    <p class="answer">Page to October 24 and it's there, on the day, <b>in the same place as every other
    Saturday</b>. The next change goes in the same way, and the PDF doesn't need re-exporting.</p>
  </div>
</div>

{QUESTIONS}"""


# ══ 3. Aqua Fitness ═══════════════════════════════════════════════════════════
FITNESS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Aqua Fitness</div>
  <h1>Aqua Fitness</h1>
  <p class="kicker">Three classes &middot; two centers &middot; 23 sessions a week</p>
  <p class="lead">Shallow Tone and Deep H2O Dynamics at the Aquatics Center, and Aqua Fitness in the CRC
  indoor pool. Drop in for $15, or free with a CRC membership.</p>

{cal("fit", "Morgan Hill Aqua Fitness — every class",
     caption="Every class at both centers, on one week.")}
</section>

<section class="wrap">
  <h2>The classes</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Class</th><th>When</th><th>Where</th></tr></thead>
    <tbody>
      <tr><td>Shallow Tone</td><td>Mon&ndash;Sat 8:00&ndash;8:55am &middot; Mon&ndash;Fri 12:00&ndash;12:55pm &middot; Mon &amp; Wed 6:45&ndash;7:40pm</td><td>Aquatics Center, Instructional Pool</td></tr>
      <tr><td>Deep H2O Dynamics</td><td>Mon&ndash;Fri 11:00&ndash;11:55am</td><td>Aquatics Center, Competition Pool</td></tr>
      <tr><td>Aqua Fitness</td><td>Mon, Wed, Fri 10:05&ndash;11:00am &middot; Tue &amp; Thu 6:50&ndash;7:45pm</td><td>CRC Indoor Pool</td></tr>
      <tr><td>Aqua Zumba</td><td>First Saturday of the month, 8:00am</td><td>Aquatics Center, Instructional Pool</td></tr>
    </tbody>
  </table>
  </div>
  <p class="capt">No lap lanes are open in the CRC pool during Aqua Fitness. Youth 12+ are welcome in
  aqua fitness classes.</p>
</section>

"""


# ══ 4. CRC Aquatics ═══════════════════════════════════════════════════════════
CRC = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; CRC Aquatics</div>
  <h1>CRC Aquatics</h1>
  <p class="kicker">Heated indoor pool &middot; three 20-yard lap lanes &middot; play area and slide</p>
  <p class="lead">Lap swim, swim lessons, aqua fitness and open play in the Centennial Recreation Center
  pool. 171 W Edmundson Avenue &middot; (408)&nbsp;782-2128.</p>

{cal("crc", "Centennial Recreation Center pool — this week",
     caption="Each block shows how many lap lanes are open.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Three lanes, counted for you</h2>
    <p>The CRC schedule carries its most useful fact in small print: <i>&ldquo;(3 Lap Lanes Open)&rdquo;</i>,
    <i>&ldquo;(1 Lap Lane Open)&rdquo;</i>, <i>&ldquo;(No Lap Lanes Open)&rdquo;</i>, and on Wednesday
    <i>&ldquo;(3 Lap Lane Open until 4:15pm) (1 Lap Lane Open from 4:15pm&ndash;6:45pm)&rdquo;</i>.</p>
    <p class="answer">On the calendar each of those is its own block with its own lane count, so a lap
    swimmer sees at a glance that <b>Wednesday at 5 means one lane beside the lessons</b>, and that
    the pool is closed from 11 until 2.</p>
  </div>
</div>

<section class="wrap">
  <div class="note">
    <span class="hd">Play area and slide</span>
    The shallow play area (1 to 2.5 ft) is open whenever the pool is; its water features are off during
    swim lessons and aqua fitness. The large slide opens Saturdays, 12:00&ndash;4:30pm.
  </div>
</section>

"""


# ══ 5. Swim Lessons ═══════════════════════════════════════════════════════════
LESSONS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Swim Lessons</div>
  <h1>Fall Swim Lessons</h1>
  <p class="kicker">At the CRC indoor pool &middot; weekdays and weekends &middot; registration open</p>
  <p class="lead">Group lessons Monday/Wednesday or Tuesday/Thursday, Saturday group lessons, and private
  lessons. Parents join in only for the Parent/Tot classes.</p>

{cal("lessons", "Morgan Hill Swim Lessons — the lesson week",
     caption="Lessons run weekday afternoons from 4:15 and weekend mornings from 8:30.")}
</section>

<section class="wrap">
  <h2>Fees</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Lessons</th><th>Non-members</th><th>CRC members</th></tr></thead>
    <tbody>
      <tr><td>Group &mdash; Mon/Wed or Tue/Thu (8 classes)</td><td class="n">$130</td><td class="n">$120</td></tr>
      <tr><td>Saturday group (4 classes)</td><td class="n">$85</td><td class="n">$75</td></tr>
      <tr><td>Private &mdash; Mon/Wed or Tue/Thu (4 lessons)</td><td class="n">$185</td><td class="n">$180</td></tr>
    </tbody>
  </table>
  </div>

  <div class="note">
    <span class="hd">While your child is in the water</span>
    One lap lane stays open during weekday lessons, and the play area is open. The calendar shows both
    beside the lesson block, so a parent can plan a swim at the same time.
  </div>
</section>

"""


# ══ 6. Lap Swim ═══════════════════════════════════════════════════════════════
LAP = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Lap Swim</div>
  <h1>Lap Swim</h1>
  <p class="kicker">Both centers &middot; no reservations &middot; free for CRC members</p>
  <p class="lead">Lap swim at the outdoor Aquatics Center and the indoor CRC pool. Drop-in is $15;
  CRC members swim free. Lanes are shared, and swimmers must be swimming laps.</p>

{cal("lap", "Morgan Hill Lap Swim — both pools",
     caption="Use the <strong>Pools</strong> menu to show one pool, or leave it on <strong>All</strong>.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>&ldquo;Please reference the current pool schedules&rdquo;</h2>
    <p>The lap swim page says lap swim <i>&ldquo;is not available all hours; please reference the
    current pool schedules for lap swim times and lane availability&rdquo;</i>, and links two PDFs with
    different layouts.</p>
    <p class="answer">This calendar is those two schedules with everything but lap swim taken out:
    <b>32 lap swim blocks a week, each with its pool and its lane count</b>, from 5am outdoors to 8pm
    indoors.</p>
  </div>
</div>

"""


# ══ 7. Splash Swim Team ═══════════════════════════════════════════════════════
SPLASH = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Splash Swim Team</div>
  <h1>Morgan Hill Splash Youth Swim</h1>
  <p class="kicker">Ages 5&ndash;18 &middot; swimming and water polo &middot; Competition Pool</p>
  <p class="lead">A year-round recreational program built on fun, family and fundamentals. Four
  practices a week, Monday&ndash;Thursday between 4:15 and 7:55pm, plus Intro to Water Polo on
  Mondays and Wednesdays. $100 a month with an active CRC membership.</p>

{cal("splash", "Morgan Hill Splash Youth Swim — practice week",
     caption="Splash practices Monday&ndash;Thursday, 4:15&ndash;7:55pm, on 12 lanes of the Competition Pool.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The other twelve lanes</h2>
    <p>From 4 to 8pm, Monday to Thursday, the pool schedule gives public lap swim <b>5 lanes</b> of 17.
    On Friday, when Splash doesn't practice, lap swim gets 11. The team is the difference, and the pool
    schedule never mentions it.</p>
    <p class="answer">On the calendar the evening pool adds up: <b>Splash on 12 lanes, lap swim on 5,
    all 17 accounted for</b>. With each group's own times, parents would see their swimmer's slot and
    lap swimmers would see exactly which lanes are theirs.</p>
  </div>
</div>

<section class="wrap">
  <p>Questions: <a href="mailto:colin.edgar@morganhill.ca.gov">Colin Edgar</a> &middot;
  <a href="https://www.morganhill.ca.gov/930/Splash-Swim-Team" target="_blank" rel="noopener">Splash Swim Team page &rarr;</a></p>
</section>

"""


PAGES = [
    ("index.html", "Aquatics &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview of the Morgan Hill aquatics page with one live Pool Relay calendar for both centers.", HUB),
    ("aquatics-center.html", "Aquatics Center &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview: the Morgan Hill Aquatics Center with a live calendar for both pools.", AC),
    ("aqua-fitness.html", "Aqua Fitness &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview: every aqua fitness class at both Morgan Hill centers on one calendar.", FITNESS),
    ("crc.html", "CRC Aquatics &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview: the Centennial Recreation Center indoor pool with lap-lane counts on every block.", CRC),
    ("swim-lessons.html", "Swim Lessons &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview: fall swim lessons at the CRC indoor pool.", LESSONS),
    ("lap-swim.html", "Lap Swim &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview: lap swim at both Morgan Hill centers on one calendar.", LAP),
    ("splash.html", "Splash Swim Team &mdash; Morgan Hill (Pool Relay preview)",
     "Unofficial preview: Morgan Hill Splash Youth Swim and the Competition Pool it trains in.", SPLASH),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        html = shell(slug, title, description, body)
        with io.open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(html)
        print(f"wrote {slug} ({len(html.encode()):,} bytes)")
